### PR TITLE
Introduce Option to Add Child Content to Annotations

### PR DESCRIPTION
**Pull request by tetracalibers**
### Summary

This PR proposes adding a new `child` option to the `Annotation` class, allowing developers to specify arbitrary child elements. This feature enables use cases such as displaying SVG icons within each annotation.

### Background

In certain scenarios, it is useful to display arbitrarily styled additional content, such as SVG icons, within annotations. For example, when using this library to draw rectangles that contain multiple annotations, you might want to display the number of annotations contained within the rectangle.

### Implementation

- Added a new `child` option to the `Annotation` class.
- The `child` option accepts any string, which is added to the element rendering the annotation via `innerHTML`.
- To facilitate layout specifications, the `child` elements set by the child option are given the `osdasl-child` class.
- Updated the "Usage" section in README.md with examples of how to use the `child` option, including notes on security considerations.

### CODE REVIEW

**Comment by leaysgur** [comment]
I understood your situation.

But by 2 reasons, I'm not go for this.

- `innerHTML` should be avoided, as you mentioned
- Render HTML fragment under host element is already achievable without changes

```ts
channel.onmessage = ({ data: message }) => {
  const { type, data } = message;
  switch (type) {
    case "annotation:added": {
      const $host = document.getElementById(data.id)!;

      const $svg = document.createElement("svg");
      // ...

      $host.appendChild($svg);
      break;
    }

  // ...
```

This may also be helpful: https://github.com/leaysgur/openseadragon-annotations-super-lite/blob/cf80b049490ab7ec6a7323815da9add0e9c71adc/demo/src/viewer/index.svelte#L168

Does this not solve your problem?

**Comment by tetracalibers** [comment]
Thank you for your suggestion. That approach hadn't occurred to me.

However, what about cases where annotation manipulation or addition is not allowed, and only viewing is supported?
In such cases, even if I try to access `$hostElement` via `channel.onmessage`, there isn't a `message.type` that would trigger.

I'm looking for a way to customize `$hostElement` at the time of annotation `restore`.

**Comment by leaysgur** [comment]
To call `restore()`, you need to prepare `annotation.id` beforehand.

This means you already know `id` to `getElementById()`.

```js
for (const { id } of annotaionsToRestore) {
  const $host = document.getElementById(id)!;

  $host.innerHTML = `...`;
}
```

https://github.com/leaysgur/openseadragon-annotations-super-lite/blob/cf80b049490ab7ec6a7323815da9add0e9c71adc/demo/src/viewer/index.svelte#L80-L81

**Comment by leaysgur** [comment]
Closing due to inactivity. Feel free to reopen if needed.

**Pull request closed without merging**
